--- 
title: "Memoirs of a bioinformatician"
author: "Payal Banerjee"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is an journaling blog for my work and reading related to bioinformatics."
---

# About me 

### Technical Expertise

Table: A simple table in Markdown.

| **SN** | **Area** | **Technique** |
| --- | --- | --- |
| 1. | Programming | Bash scripting, Python, R, |
| 2. | Next Generation Sequencing Pipelines | RNA Sequencing, DNA Sequencing, Microbiome, T-cell Receptor Sequencing, Chip Seq, Single Cell sequencing, Microarray |
| 3. | Cloud Resource NGS Platforms | DNA Nexus, Illumina Basepace (including DRAGEN), Galaxy, Cavatica, GenePattern |
| 4. | Cloud Computing | AWS EC2 and S3 |
| 5. | Operating Systems | Unix (Linux,Ubuntu, Centos, macOS) |
| 6. | Website Management | Github Pages , Relational Databases (RDMS), MySQL, HTML, PHP, Apache, Data Model Design, Drupal |

          
**Education:**

| **SN** | **Degree** | **Field** | **University/College** | **Timeline** | **Place** |
| --- | --- | --- | --- | --- | --- |
| 1. | M.S. | Bioinformatics | Georgetown University | 2014-2015 | Washington, DC, USA |
| 2. | M.S. | Biochemistry | Bangalore University | 2011-2013 | Bangalore, India |
| 3. | B.S. | Biotechnology, Microbiology, Biochemistry | Bangalore University | 2008-2011 | Bangalore, India |

**Publications:**

| Title | Journal Name | 
| --- | --- | --- | --- | --- | 
| Immunotherapy of Relapsed and Refractory Solid Tumors With Ex Vivo Expanded Multi-Tumor Associated Antigen Specific Cytotoxic T Lymphocytes: A Phase I Study | [Journal of Clinical Oncology](https://ascopubs.org/doi/10.1200/JCO.19.00177) | 
| Enabling precision medicine in neonatology, an integrated repository for preterm birth research | [Scientific Data](https://www.nature.com/articles/sdata2018219)|
|A cross-sectional analysis of the urine microbiome of children with neuropathic bladders|[Science Direct](https://doi.org/10.1016/j.jpurol.2020.02.005)|
|Identification of amygdala-expressed genes associated with autism spectrum disorder|[Molecular Autism](https://doi.org/10.1186/s13229-020-00346-1)|
|Endothelin-1 signaling maintains glial progenitor proliferation in the postnatal subventricular zone|[Nature Communications](https://doi.org/10.1038/s41467-020-16028-8)|


**[Orchid ID](https://orcid.org/0000-0003-1599-0679)**
